### ISSUE TITLE
can I use this to transpose a musicxml file

### ISSUE THREAD

**Issue by benlieb** [kddeisz/musicxml#9]
Trying to create an app for myself (browser-based) that will show musicxml docs (rendered in JS) in different keys (transpose).

If I can't do it with this gem do you know a tool in ruby or JS that can transpose musicxml?

Thanks

**Comment by kddnewton** [comment]
Yeah you could use this. It might be easier to check out something like vexflow (https://github.com/0xfe/vexflow).
